name: new_view
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+1
environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  syncfusion_flutter_pdfviewer: ^20.2.44-beta
  http: ^0.13.6


dev_dependencies:
  flutter_test:
    sdk: flutter




flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/bangla_version/class_1/bangla.PNG
    - asset/bangla_version/class_1/English.PNG
    - asset/bangla_version/class_1/Math.PNG
    - asset/bangla_version/class_1/Bangla.pdf
    - asset/bangla_version/class_1/Englis.pdf
    - asset/bangla_version/class_1/Math.pdf
    - asset/bangla_version/class_2/bangla.PNG
    - asset/bangla_version/class_2/english.PNG
    - asset/bangla_version/class_2/math.PNG
    - asset/bangla_version/class_2/Bangla2.pdf
    - asset/bangla_version/class_2/English2.pdf
    - asset/bangla_version/class_2/Math2.pdf
    - asset/bangla_version/class_3/Bangla3.PNG
    - asset/bangla_version/class_3/English3.PNG
    - asset/bangla_version/class_3/Math3.PNG
    - asset/bangla_version/class_3/Science3.PNG
    - asset/bangla_version/class_3/Islam3.PNG
    - asset/bangla_version/class_3/BGS3.PNG
    - asset/bangla_version/class_3/Buddho3.PNG
    - asset/bangla_version/class_3/Cristian3.PNG
    - asset/bangla_version/class_5/1.PNG
    - asset/nctb.png
    - asset/bangla.PNG
    - asset/english.PNG
    - asset/icon.png
    - asset/bangla_version/class_4/bangla4.PNG
    - asset/bangla_version/class_4/bgs4.PNG
    - asset/bangla_version/class_4/bodhhu4.PNG
    - asset/bangla_version/class_4/cristan.PNG
    - asset/bangla_version/class_4/english4.PNG
    - asset/bangla_version/class_4/hindhu.PNG
    - asset/bangla_version/class_4/islam4.PNG
    - asset/bangla_version/class_4/math4.PNG
    - asset/bangla_version/class_4/science4.PNG
    - asset/bangla_version/class_5/2.PNG
    - asset/bangla_version/class_5/3.PNG
    - asset/bangla_version/class_5/4.PNG
    - asset/bangla_version/class_5/5.PNG
    - asset/bangla_version/class_5/6.PNG
    - asset/bangla_version/class_5/7.PNG
    - asset/bangla_version/class_5/8.PNG
    - asset/bangla_version/class_5/9.PNG
    - asset/bangla_version/class_6/1.PNG
    - asset/bangla_version/class_6/2.PNG
    - asset/bangla_version/class_6/3.PNG
    - asset/bangla_version/class_6/4.PNG
    - asset/bangla_version/class_6/5.PNG
    - asset/bangla_version/class_6/6.PNG
    - asset/bangla_version/class_6/7.PNG
    - asset/bangla_version/class_6/8.PNG
    - asset/bangla_version/class_6/9.PNG
    - asset/bangla_version/class_6/10.PNG
    - asset/bangla_version/class_6/11.PNG
    - asset/bangla_version/class_7/1.PNG
    - asset/bangla_version/class_7/2.PNG
    - asset/bangla_version/class_7/3.PNG
    - asset/bangla_version/class_7/4.PNG
    - asset/bangla_version/class_7/5.PNG
    - asset/bangla_version/class_7/6.PNG
    - asset/bangla_version/class_7/7.PNG
    - asset/bangla_version/class_7/8.PNG
    - asset/bangla_version/class_7/9.PNG
    - asset/bangla_version/class_7/10.PNG
    - asset/bangla_version/class_7/11.PNG
    - asset/bangla_version/class_7/12.PNG
    - asset/bangla_version/class_7/13.PNG
    - asset/bangla_version/class_7/14.PNG




  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
