name: new_view
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+1
environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  syncfusion_flutter_pdfviewer: ^20.2.44-beta
  http: ^0.13.6


dev_dependencies:
  flutter_test:
    sdk: flutter




flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/bangla_version/class_1/bangla.PNG
    - asset/bangla_version/class_1/English.PNG
    - asset/bangla_version/class_1/Math.PNG
    - asset/bangla_version/class_1/Bangla.pdf
    - asset/bangla_version/class_1/Englis.pdf
    - asset/bangla_version/class_1/Math.pdf
    - asset/bangla_version/class_2/bangla.PNG
    - asset/bangla_version/class_2/english.PNG
    - asset/bangla_version/class_2/math.PNG
    - asset/bangla_version/class_2/Bangla2.pdf
    - asset/bangla_version/class_2/English2.pdf
    - asset/bangla_version/class_2/Math2.pdf
    - asset/bangla_version/class_3/Bangla3.PNG
    - asset/bangla_version/class_3/English3.PNG
    - asset/bangla_version/class_3/Math3.PNG
    - asset/bangla_version/class_3/Science3.PNG
    - asset/bangla_version/class_3/Islam3.PNG
    - asset/bangla_version/class_3/BGS3.PNG
    - asset/bangla_version/class_3/Buddho3.PNG
    - asset/bangla_version/class_3/Cristian3.PNG
    - asset/nctb.png
    - asset/bangla.PNG
    - asset/english.PNG
    - asset/icon.png
    - asset/bangla_version/class_4/bangla4.PNG
    - asset/bangla_version/class_4/bgs4.PNG
    - asset/bangla_version/class_4/bodhhu4.PNG
    - asset/bangla_version/class_4/cristan.PNG
    - asset/bangla_version/class_4/english4.PNG
    - asset/bangla_version/class_4/hindhu4.PNG
    - asset/bangla_version/class_4/islam4.PNG
    - asset/bangla_version/class_4/math4.PNG
    - asset/bangla_version/class_4/science4.PNG
    - asset/bangla_version/class_5/bangla5.PNG
    - asset/bangla_version/class_5/bgs5.PNG
    - asset/bangla_version/class_5/buddho5.PNG
    - asset/bangla_version/class_5/cristan5.PNG
    - asset/bangla_version/class_5/english5.PNG
    - asset/bangla_version/class_5/hindu5.PNG
    - asset/bangla_version/class_5/islam5.PNG
    - asset/bangla_version/class_5/math5.PNG
    - asset/bangla_version/class_5/biggan5.PNG
    - asset/bangla_version/class_6/bangla6.PNG
    - asset/bangla_version/class_6/budhu6.PNG
    - asset/bangla_version/class_6/english6.PNG
    - asset/bangla_version/class_6/english6.PNG
    - asset/bangla_version/class_6/hindhu6.PNG
    - asset/bangla_version/class_6/islam6.PNG
    - asset/bangla_version/class_6/math6.PNG
    - asset/bangla_version/class_6/biggan6.PNG
    - asset/bangla_version/class_6/etihas6.PNG
    - asset/bangla_version/class_7/bodhu7.PNG
    - asset/bangla_version/class_7/bangla7.PNG
    - asset/bangla_version/class_7/cristan7.PNG
    - asset/bangla_version/class_7/english7.PNG
    - asset/bangla_version/class_7/hindhu7.PNG
    - asset/bangla_version/class_7/islam7.PNG
    - asset/bangla_version/class_7/math7.PNG
    - asset/bangla_version/class_7/science7.PNG
    - asset/bangla_version/class_7/etihas7.PNG
    - asset/bangla_version/class_7/biggan7.PNG
    - asset/bangla_version/class_8/anado8.PNG
    - asset/bangla_version/class_8/arabik8.PNG
    - asset/bangla_version/class_8/bangla8.PNG
    - asset/bangla_version/class_8/banglag8.PNG
    - asset/bangla_version/class_8/biggan8.PNG
    - asset/bangla_version/class_8/bodhu8.PNG
    - asset/bangla_version/class_8/charukaru8.PNG
    - asset/bangla_version/class_8/english8.PNG
    - asset/bangla_version/class_8/englishg8.PNG
    - asset/bangla_version/class_8/hindu8.PNG
    - asset/bangla_version/class_8/ict8.PNG
    - asset/bangla_version/class_8/islam8.PNG
    - asset/bangla_version/class_8/krisi8.PNG
    - asset/bangla_version/class_8/kristan8.PNG
    - asset/bangla_version/class_8/math8.PNG
    - asset/bangla_version/class_8/sasto8.PNG
    - asset/bangla_version/class_8/somaj8.PNG
    - asset/bangla_version/class_8/songiscrity8.PNG
    - asset/bangla_version/class_8/songit8.PNG
    - asset/bangla_version/class_9&10/banglag9.PNG
    - asset/bangla_version/class_9&10/banglasohopat.PNG
    - asset/bangla_version/class_9&10/budhu9.PNG
    - asset/bangla_version/class_9&10/carierr9.PNG
    - asset/bangla_version/class_9&10/charukaru9.PNG
    - asset/bangla_version/class_9&10/cristan9.PNG
    - asset/bangla_version/class_9&10/etiihas9.PNG
    - asset/bangla_version/class_9&10/garosto9.PNG
    - asset/bangla_version/class_9&10/hisabbiggan9.PNG
    - asset/bangla_version/class_9&10/jibbiggan9.PNG
    - asset/bangla_version/class_9&10/krici9.PNG
    - asset/bangla_version/class_9&10/poli9.PNG
    - asset/bangla_version/class_9&10/proniti9.PNG
    - asset/bangla_version/class_9&10/rosayon9.PNG
    - asset/bangla_version/class_9&10/saririk9.PNG
    - asset/bangla_version/class_9&10/somaj9.PNG
    - asset/bangla_version/class_9&10/songit.PNG
    - asset/bangla_version/class_9&10/vugol9.PNG
    - asset/bangla_version/class_9&10/arabiks9.PNG




  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
