name: new_view
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  syncfusion_flutter_pdfviewer: ^20.2.44-beta
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/class_1/bangla.PNG
    - asset/class_1/English.PNG
    - asset/class_1/Math.PNG
    - asset/class_1/Bangla.pdf
    - asset/class_1/Englis.pdf
    - asset/class_1/Math.pdf
    - asset/class_2/bangla.PNG
    - asset/class_2/english.PNG
    - asset/class_2/math.PNG
    - asset/class_2/Bangla2.pdf
    - asset/class_2/English2.pdf
    - asset/class_2/Math2.pdf
    - asset/class_3/Bangla3.PNG
    - asset/class_3/English3.PNG
    - asset/class_3/Math3.PNG
    - asset/class_3/Science3.PNG
    - asset/class_3/Islam3.PNG
    - asset/class_3/BGS3.PNG
    - asset/class_3/Buddho3.PNG
    - asset/class_3/Cristian3.PNG
    - asset/nctb.png


  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
